@extends('layouts.default')
@section('content')
        <section id="content">
          <section class="hbox stretch">
          <aside class="aside-md bg-white b-r" id="subNav">
              <div class="wrapper b-b header">Supplier Manager</div>
              <ul class="nav">

          <ul class="nav">
           <li class="b-b b-light"><a href="/pharmacy.dashboard"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Overview</a></li>
                <li class="b-b b-light"><a href="/supplier-payments"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Payments</a></li>
                <li class="b-b b-light"><a href="/supplier-purchases"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Purchases</a></li>
                <li class="b-b b-light"><a href="/supplier-bills"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Invoices</a></li>
                <li class="b-b b-light"><a href="/drugs-pending-approval"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Pending Approval</a></li>
               
              </ul>
            </aside>
            <aside>
              <section class="vbox">
                <header class="panel-heading">
                    <form action="/search-invoice" method="GET">


                      <div class="input-group text-ms">
                        
                        <div class="col-md-8">
                        <input type="text" name='search' id='search' class="input-sm form-control" placeholder="Search by number, supplier, item">
                        </div>
                       
                         <div class="col-md-4">
                        <input type="text" name='invoice_period' id='invoice_period' class="input-sm form-control" placeholder="Search by patient, test, status">
                        </div>

                        <div class="input-group-btn">
                           <button class="btn btn-sm btn-success" type="submit">Search Invoice!</button>
                        </div>
                      </div>



                      </form>
                    </header>
                <section class="scrollable wrapper w-f">
                  <section class="panel panel-default">
                  <header class="panel-heading font-bold">Supplier Invoices
                                 <a href="#new-invoice" class="bootstrap-modal-form-open" data-toggle="modal"><span class="badge bg-info pull-right"> Add New Drug Invoice +</span></a>

                                 <a href="#new-invoice-non-drug" class="bootstrap-modal-form-open" data-toggle="modal"><span class="badge bg-warning pull-right"> Add New Non-Drug Invoice +</span></a>

                                </header>
                    <div class="table-responsive">
                      <table class="table table-striped m-b-none text-sm" width="100%">
                        <thead>
                          <tr>
                           <th>#</th>
                            <th>Invoice Date </th>
                            <th>Invoice # </th>
                            <th>Supplier</th>
                             <th>Type</th>
                            <th>Generated By</th>
                            <th>Generated On</th>
                            <th>Amount (GHS)</th>
                            <th width="20"></th>
                            <th width="30"></th>
                             <th width="20"></th>
                            <th width="30"></th>
                            <th width="20"></th>
                            <th width="30"></th>
                          </tr>
                        </thead>
                         <tbody>
                         @foreach( $items as $key => $item )
                          <tr>
                            
                           <td>{{ ++$key }}</td>
                            <td>{{ $item->invoice_date }}</td>
                             <td>{{ $item->invoice_number }}</td>
                            <td>{{ $item->supplier }}</td>
                            <td>{{ $item->category }}</td>
                            <td>{{ $item->created_by }}</td>
                            <td>{{ $item->created_on }}</td>
                            <td>{{ number_format($item->cost, 2, '.', ',') }}</td>
                             <td>{{ $item->status }}</td>
                            <td>{{ $item->upload_state }}</td>

                            @if($item->category == 'Drugs')
                             <td><a href="#new-invoice" class="bootstrap-modal-form-open" onclick="getInvoicedetail('{{ $item->invoice_number }}')"  id="edit" name="edit" data-toggle="modal" alt="edit"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit Invoice"></i></a>
                             </td>
                             @else
                            
                             <td><a href="#new-invoice-non-drug" class="bootstrap-modal-form-open" onclick="getInvoicedetailConsumable('{{ $item->invoice_number }}')"  id="edit" name="edit" data-toggle="modal" alt="edit"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit Invoice"></i></a>

                             @endif


                             @role(['Pharmacist','System Admin'])
                              @if( $item->upload_state != 'Uploaded')
                              <td><a href="#modal_check_in" class="bootstrap-modal-form-open" onclick="approveDetails('{{ $item->invoice_number }}','{{ $item->supplier }}')"  id="edit" name="edit" data-toggle="modal" alt="edit"><i class="fa fa-thumbs-up" data-toggle="tooltip" data-placement="top" title="" data-original-title="Approve Invoice"></i></a>
                             </td>
                            
                              <td><a href="#upload-invoice" class="bootstrap-modal-form-open" onclick="getInvoicedetail('{{ $item->invoice_number }}')"  id="edit" name="edit" data-toggle="modal" alt="edit"><i class="fa fa-upload" data-toggle="tooltip" data-placement="top" title="" data-original-title="Upload invoice items to shelf"></i></a>
                             </td>
                             @else
                             @endif
                             <td><a href="#modal_check_in" class="bootstrap-modal-form-open" onclick="deleteDetails('{{ $item->invoice_number }}','{{ $item->supplier }}')"  id="edit" name="edit" data-toggle="modal" alt="edit"><i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete Invoice"></i></a>
                             </td>
                             <td><a href="/print-store-voucher/{{ $item->invoice_number }}" class="bootstrap-modal-form-open"  id="edit" name="edit" data-toggle="modal" alt="edit"><i class="fa fa-print" data-toggle="tooltip" data-placement="top" title="" data-original-title="Print Received Voucher"></i></a>
                             </td>
                             @endrole
                            
                          </tr>
                         @endforeach  
                        </tbody>
 
                      </table>
                    </div>
                  </section>
                </section>
                <footer class="footer bg-white b-t">
                  <div class="row text-center-xs">
                    <div class="col-md-6 hidden-sm">
                      <p class="text-muted m-t">
                      </p>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right text-center-xs">                
                     
                      {!!$items->render()!!} 
                        
                    </div>
                  </div>
                </footer>
              </section>
            </aside>
          </section>
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
        </section>
@stop




<script src="{{ asset('/js/jquery.min.js')}}"></script>
<script src="{{ asset('/event_components/jquery.min.js')}}"></script>

<script type="text/javascript">
$(function() {

    var start = moment().subtract(29, 'days');
    var end = moment();

    function cb(start, end) {
        $('#invoice_period span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }

    $('#invoice_period').daterangepicker({
        startDate: start,
        endDate: end,
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);

    cb(start, end);
    
});


</script>


<script type="text/javascript">
$(document).ready(function () {
   
    $('#medication').select2();
    $('#supplier').select2({tags: true});


                  $('#new-medication select[name="classification"]').select2({
                  tags: true
                  });
                  $('#new-medication select[name="supplier"]').select2({
                  tags: true
                  });
                   $('#new-medication select[name="drug_form"]').select2({
                  tags: true
                  });
                    $('#new-medication select[name="brand"]').select2({
                  tags: true
                  });


                     $('#new-invoice-non-drug select[name="consumable_supplier"]').select2({
                  tags: true
                  });

                       $('#new-invoice-non-drug select[name="consumable"]').select2({
                  tags: true
                  });



   


  });
</script>

<script type="text/javascript">
$(function () {
  $('#new-invoice input[name="invoice_date"]').daterangepicker({
     "maxDate": moment(),
      "singleDatePicker":true,
      "autoApply": true,
      "showDropdowns": true,
      "locale": {
      "format": "DD/MM/YYYY",
      "separator": " - ",
    }
  });
});
</script>

<script type="text/javascript">
$(function () {
  $('#new-invoice-non-drug input[name="consumable_invoice_date"]').daterangepicker({
     "maxDate": moment(),
      "singleDatePicker":true,
      "autoApply": true,
      "showDropdowns": true,
      "locale": {
      "format": "DD/MM/YYYY",
      "separator": " - ",
    }
  });
});
</script>

<script type="text/javascript">
$(function () {
  $('#new-medication input[name="expiry_date"]').daterangepicker({
     "minDate": moment(),
      "singleDatePicker":true,
      "autoApply": true,
      "showDropdowns": true,
      "locale": {
      "format": "DD/MM/YYYY",
      "separator": " - ",
    }
  });
});
</script>

<script>

function getdrugdetail()
{ 
   //alert($('#medication').val());

  $.get("/get-drug-info",
          {"medication": $('#medication').val()},
          function(json)
          {
    
              $('#unit_price').val(json['unit_price']);
                $('#quantity').val("");

               
                
              //}
          },
          'json').fail(function(msg) {
          alert(msg.status + " " + msg.statusText);
        });

}


function getconsumabledetail()
{ 
   //alert($('#medication').val());

  $.get("/get-consumable-info",
          {"consumable": $('#consumable').val()},
          function(json)
          {
    
              $('#consumable_unit_price').val(json['unit_price']);
                $('#quantity').val("");

                
                
              //}
          },
          'json').fail(function(msg) {
          alert(msg.status + " " + msg.statusText);
        });

}


function getInvoicedetail(id)
{ 
  //alert(id);
   $.get("/edit-supplier-bills",
          {"id":id},
          function(json)
          {
            

                $('#new-invoice input[name="invoice_number"]').val(json.invoice_number);
                $('#new-invoice input[name="invoice_date"]').val(json.invoice_date);
                $('#new-invoice select[name="supplier"]').val(json.supplier);
                $('#new-invoice input[name="invoice_remark"]').val(json.remark);
                $('#new-invoice input[name="invoice_description"]').val(json.note);
                $('#supplier').select2({tags: true});
           
               loadInvoices();
               loadInvoicestoShelf();
              //}
          },'json').fail(function(msg) {
          alert(msg.status + " " + msg.statusText);
        });


}


function getInvoicedetailConsumable(id)
{ 

   //alert(id);
   $.get("/edit-supplier-bills-consumables",


          {"id":id},
          function(json)
          {
            

                $('#new-invoice-non-drug input[name="consumable_invoice_number"]').val(json.consumable_invoice_number);
                $('#new-invoice-non-drug input[name="consumable_invoice_date"]').val(json.consumable_invoice_date);
                $('#new-invoice-non-drug select[name="consumable_supplier"]').val(json.consumable_supplier);
                $('#new-invoice-non-drug input[name="consumable_invoice_remark"]').val(json.consumable_remark);
                $('#new-invoice-non-drug input[name="consumable_invoice_description"]').val(json.consumable_note);
                $('#consumable_supplier').select2({tags: true});
           
               loadInvoicesConsumable();
               loadInvoicestoShelfConsumable();
              //}
          },'json').fail(function(msg) {
          alert(msg.status + " " + msg.statusText);
        });


}


function addInvoices()
{
if($('#invoice_number').val()!= "")
{

    $.get('/add-drug-invoice',
        {
          "invoice_number": $('#invoice_number').val(),
          "invoice_date": $('#invoice_date').val(),
          "invoice_description": $('#invoice_description').val(),
          "invoice_remark": $('#invoice_remark').val(),

          "medication": $('#medication').val(),
          "supplier": $('#supplier').val(),
          "quantity":  $('#quantity').val(),
          "unit_price":  $('#unit_price').val()
                              
        },
        function(data)
        { 
          
          $.each(data, function (key, value) {
        if(data["OK"])
        {
         
          loadInvoices();
          $('#invoice_number').val()!= ""
        }
        else
        {
          sweetAlert("Invoice failed to add!");
        }
      });
                                        
        },'json');
  }
  else
    {sweetAlert("Please select a medication!");}
}


function addInvoicesConsumable()
{
if($('#consumable_invoice_number').val()!= "")
{

    $.get('/add-consumable-invoice',
        {
          "consumable_invoice_number": $('#consumable_invoice_number').val(),
          "consumable_invoice_date": $('#consumable_invoice_date').val(),
          "consumable_invoice_description": $('#consumable_invoice_description').val(),
          "consumable_invoice_remark": $('#consumable_invoice_remark').val(),

          "consumable": $('#consumable').val(),
          "consumable_supplier": $('#consumable_supplier').val(),
          "consumable_quantity":  $('#consumable_quantity').val(),
          "consumable_unit_price":  $('#consumable_unit_price').val()
                              
        },
        function(data)
        { 
          
          $.each(data, function (key, value) {
        if(data["OK"])
        {
         
          loadInvoicesConsumable();
          $('#consumable_invoice_number').val()!= ""
        }
        else
        {
          sweetAlert("Invoice failed to add!");
        }
      });
                                        
        },'json');
  }
  else
    {sweetAlert("Please select a medication!");}
}

function loadInvoices()
   {
         
        
        $.get('/fetch-invoices',
          {
            "invoice_number": $('#invoice_number').val()
          },
          function(data)
          { 

            $('#invoicesTable tbody').empty();
            $.each(data, function (key, value) 
            {           
           $('#invoicesTable tbody').append('<tr><td>'+ value['description'] +'</td><td>'+ value['quantity'] +'</td><td>'+ value['unit_price'] +'</td><td>'+ value['unit_price']* value['quantity'] +'</td><td><a a href="#"><i onclick="removeitem(\''+value['id']+'\',\''+value['description']+'\')" class="fa fa-trash-o"></i></a></td></tr>');
            });
                                          
         },'json');      
    }

  function loadInvoicesConsumable()
   {
         
        
        $.get('/fetch-invoices-consumable',
          {
            "consumable_invoice_number": $('#consumable_invoice_number').val()
          },
          function(data)
          { 

            $('#invoicesTableConsmable tbody').empty();
            $.each(data, function (key, value) 
            {           
           $('#invoicesTableConsmable tbody').append('<tr><td>'+ value['description'] +'</td><td>'+ value['quantity'] +'</td><td>'+ value['unit_price'] +'</td><td>'+ value['unit_price']* value['quantity'] +'</td><td><a a href="#"><i onclick="removeitem(\''+value['id']+'\',\''+value['description']+'\')" class="fa fa-trash-o"></i></a></td></tr>');
            });
                                          
         },'json');      
    }

    function loadInvoicestoShelf()
   {
         
        
        $.get('/fetch-invoices-for-upload',
          {
            "invoice_number": $('#invoice_number').val()
          },
          function(data)
          { 

            $('#invoicesTableShelf tbody').empty();
            $.each(data, function (key, value) 
            {           
           $('#invoicesTableShelf tbody').append('<tr><td>'+ value['description'] +'</td><td>'+ value['quantity'] +'</td><td>'+ value['unit_price'] +'</td><td>'+ value['unit_price']* value['quantity'] +'</td><td><a a href="#"><i onclick="uploadDetails(\''+value['id']+'\',\''+value['description']+'\')" class="fa fa-upload"></i></a></td></tr>');
            });
                                          
         },'json');      
    }



  function deleteDetails(id,name)
   {
      swal({   
        title: "Are you sure?",   
        text: "Do you want to remove "+ name +" from list?",   
        type: "warning",   
        showCancelButton: true,   
        confirmButtonColor: "#DD6B55",   
        confirmButtonText: "Yes, delete it!",   
        cancelButtonText: "No, cancel plx!",   
        closeOnConfirm: false,   
        closeOnCancel: false }, 
        function(isConfirm){   
          if (isConfirm) 
          { 
          $.get('/delete-invoice',
          {
             "ID": id 
          },
          function(data)
          { 
            
            $.each(data, function (key, value) 
            {
            if(value == "OK")
            {
              swal("Deleted!", name +" was removed from list.", "success"); 
               location.reload(true);
             }
            else
            { 
              swal("Cancelled","Failed to be removed from list.", "error");
              
            }
           
        });
                                          
          },'json');    
           
             } 
        else {     
          swal("Cancelled","Failed to be removed from list.", "error");   
        } });
   }


   function removeitem(id,name)
   {
      swal({   
        title: "Are you sure?",   
        text: "Do you want to remove "+ name +" from list?",   
        type: "warning",   
        showCancelButton: true,   
        confirmButtonColor: "#DD6B55",   
        confirmButtonText: "Yes, delete it!",   
        cancelButtonText: "No, cancel plx!",   
        closeOnConfirm: false,   
        closeOnCancel: false }, 
        function(isConfirm){   
          if (isConfirm) 
          { 
          $.get('/delete-invoice-item',
          {
             "ID": id 
          },
          function(data)
          { 
            
            $.each(data, function (key, value) 
            {
            if(value == "OK")
            {
              swal("Deleted!", name +" was removed from list.", "success"); 
              loadInvoices();
             }
            else
            { 
              swal("Cancelled","Failed to be removed from list.", "error");
              
            }
           
        });
                                          
          },'json');    
           
             } 
        else {     
          swal("Cancelled","Failed to be removed from list.", "error");   
        } });
   }



  function approveDetails(id,name)
   {

      swal({   
        title: "Are you sure?",   
        text: "Do you want to approve "+ name +" from list?",   
        type: "warning",   
        showCancelButton: true,   
        confirmButtonColor: "#DD6B55",   
        confirmButtonText: "Yes, Approve it!",   
        cancelButtonText: "No, cancel plx!",   
        closeOnConfirm: false,   
        closeOnCancel: false }, 
        function(isConfirm){   
          if (isConfirm) 
          { 
          $.get('/approve-invoice',
          {
             "ID": id 
          },
          function(data)
          { 
            
            $.each(data, function (key, value) 
            {
            if(value == "OK")
            {
              swal("Success!", name +" was removed from list.", "success"); 
               location.reload(true);
             }
            else
            { 
              swal("Cancelled","Failed to be removed from list.", "error");
              
            }
           
        });
                                          
          },'json');    
           
             } 
        else {     
          swal("Cancelled","Failed to be removed from list.", "error");   
        } });
   }


function uploadDetails(id,name)
   {
        //alert(id);

      swal({   
        title: "Are you sure?",   
        text: "Do you want to upload "+ name +" from stock to shelf?",   
        type: "warning",   
        showCancelButton: true,   
        confirmButtonColor: "#DD6B55",   
        confirmButtonText: "Yes, upload it!",   
        cancelButtonText: "No, cancel plx!",   
        closeOnConfirm: false,   
        closeOnCancel: false }, 
        function(isConfirm){   
          if (isConfirm) 
          { 
          $.get('/upload-invoice',
          {
             "ID": id 
          },
          function(data)
          { 
            
            $.each(data, function (key, value) 
            {
            if(value == "OK")
            {
             swal("Success!", name +" was uploaded.", "success"); 
               //location.reload(true);

               loadInvoicestoShelf();
             }
            else
            { 
              swal("Cancelled","Failed to upload.", "error");
              
            }
           
        });
                                          
          },'json');    
           
             } 
        else {     
          swal("Cancelled","Failed to upload.", "error");   
        } });
   }


</script>

<div class="modal fade" id="new-invoice" style="height:900px">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">New Drug Invoice</h4>
        </div>
        <div class="modal-body">
          <p></p>
                      <section class="vbox">
                    <section class="scrollable">
                      <div class="tab-content">
                        <div class="tab-pane active" id="individual">
                           <form  class="bootstrap-modal-form" method="post" action="/add-drug-category" class="panel-body wrapper-lg">
                          @include('pharmacy/invoice') 
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                      </form>
                        </div>
                  
                  
                        </div>
                        </section>
                        </section>
                      </div>
                    
        </div>
        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->


    <div class="modal fade" id="new-invoice-non-drug" style="height:900px">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">New Non-Drug Invoice</h4>
        </div>
        <div class="modal-body">
          <p></p>
                      <section class="vbox">
                    <section class="scrollable">
                      <div class="tab-content">
                        <div class="tab-pane active" id="individual">
                           <form  class="bootstrap-modal-form" method="post" action="/add-drug-category" class="panel-body wrapper-lg">
                          @include('pharmacy/invoice_misc') 
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                      </form>
                        </div>
                  
                  
                        </div>
                        </section>
                        </section>
                      </div>
                    
        </div>
        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->


<div class="modal fade" id="new-medication" size="600">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add New Drug</h4>
        </div>
        <div class="modal-body">
          <p></p>
                      <section class="vbox">
                    <header class="header bg-light bg-gradient">
                      <ul class="nav nav-tabs nav-white">
                          <li class="active"><a href="#equitytab" data-toggle="tab">Drug Details</a></li>
                      </ul>
                    </header>
                    <section class="scrollable">
                      <div class="tab-content">
                        <div class="tab-pane active" id="individual">
                           <form  class="bootstrap-modal-form" data-validate="parsley" method="post" action="/save-drug" class="panel-body wrapper-lg">
                           @include('pharmacy/new_drug')
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                      </form>
                        </div>
                      </div>
                    </section>
                  </section>
        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
</div>

<div class="modal fade" id="upload-invoice" style="height:900px">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Upload Invoice to Shelf</h4>
        </div>
        <div class="modal-body">
          <p></p>
                      <section class="vbox">
                    <section class="scrollable">
                      <div class="tab-content">
                        <div class="tab-pane active" id="individual">
                           <form  class="bootstrap-modal-form" method="post" action="" class="panel-body wrapper-lg">
                          @include('pharmacy/bulkupload') 
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                      </form>
                        </div>
                  
                  
                        </div>
                        </section>
                        </section>
                      </div>
                    
        </div>
        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->


